/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "My RSS Feed": "My RSS Feed",
    "New URL: ": "New URL: ",
    "Set": "Set",
    "Feed URLs: ": "Feed URLs: ",
    "Article Length": "Article Length",
    "Reset": "Reset",
    "Done": "Done",
    "Invalid Feed": "Invalid Feed",
    "%s does not appear to be a valid RSS or Atom feed.": "%s does not appear to be a valid RSS or Atom feed.",
    "No Items Found": "No Items Found",
    "The feed does not contain any entries.": "The feed does not contain any entries.",
    "No items matched the search terms.": "No items matched the search terms.",
    "Nothing To Display": "Nothing To Display",
    "The feed does not contain any entries within the specified criteria.": "The feed does not contain any entries within the specified criteria.",
    "Loading": "Loading",
    "%s new": "%s new",
    "No Feed Specified": "No Feed Specified",
    "Please specify a valid feed URL.": "Please specify a valid feed URL."
};
